"""Async AG-UI runs: Redis-Stream relay (webhook mode).

The Modal planner runs detached (900 s budget) and POSTs AG-UI events to
the Heroku webhook ``POST /api/research-agent/agui-events``. This module
stores them in a Redis Stream (`XADD`, MAXLEN-capped, 6 h TTL) and the
browser reads them back from ``GET /api/research-agent/agui-stream`` as a
normal SSE feed — same wire format, but generated by Heroku with
heartbeats, so Heroku's 55 s router idle timeout and Modal's HTTP task
timeout can no longer kill a long turn mid-stream. Reconnects resume from
the last event id (Rule R28).

When Redis is not configured the same relay runs on an in-process store
(single-dyno deploys); the API is identical.
"""
from __future__ import annotations

import asyncio
import json
import logging
import time
import uuid
from dataclasses import dataclass, field
from typing import Any, AsyncIterator

from app.cache.redis_client import get_redis, open_redis

logger = logging.getLogger(__name__)

_STREAM_MAXLEN = 20_000
_TTL_S = 6 * 3600
_XREAD_BLOCK_MS = 15_000
# Watchdogs: the bridge dies only on SILENCE (no events for 10 min) or an
# absolute cap of 60 min. A run that keeps producing events is alive, no
# matter how long it takes — the old fixed 20-min wall clock killed
# healthy long runs ("timed out before finishing", production 2026-09-14).
_MAX_IDLE_S = 10 * 60
_MAX_TOTAL_S = 60 * 60


def _stream_key(thread_id: uuid.UUID | str, run_id: str) -> str:
    return f"agui:{thread_id}:{run_id}"


def _run_key(run_id: str) -> str:
    return f"agui-run:{run_id}"


@dataclass
class MemoryRun:
    thread: str | None = None
    events: list[tuple[str, dict[str, Any]]] = field(default_factory=list)
    done: bool = False

_MEMORY: dict[str, MemoryRun] = {}
_MEMORY_SWEEP_AT = 0.0


def _memory_run(run_id: str) -> MemoryRun:
    _sweep_memory()
    run = _MEMORY.get(run_id)
    if run is None:
        run = _MEMORY[run_id] = MemoryRun()
    return run


def _sweep_memory() -> None:
    """Drop finished runs older than the TTL (bounded memory, single dyno)."""
    global _MEMORY_SWEEP_AT
    now = time.monotonic()
    if now - _MEMORY_SWEEP_AT < 60:
        return
    _MEMORY_SWEEP_AT = now
    for key in [k for k, v in _MEMORY.items() if v.done]:
        _MEMORY.pop(key, None)


async def register_run(thread_id: uuid.UUID | str, run_id: str) -> None:
    """Bind run_id → thread for webhook authorization, with TTL."""
    redis = await get_redis()
    if redis is not None:
        await redis.set(_run_key(run_id), str(thread_id), ex=_TTL_S)
        return
    _memory_run(run_id).thread = str(thread_id)


async def run_thread_id(run_id: str) -> str | None:
    redis = await get_redis()
    if redis is not None:
        value = await redis.get(_run_key(run_id))
        return value.decode() if isinstance(value, bytes) else (str(value) if value else None)
    run = _MEMORY.get(run_id)
    return run.thread if run else None


async def append_events(thread_id: uuid.UUID | str, run_id: str, events: list[dict[str, Any]]) -> int:
    """Append AG-UI events; mark the stream done on RUN_FINISHED/RUN_ERROR."""
    if not events:
        return 0
    redis = await get_redis()
    key = _stream_key(thread_id, run_id)
    if redis is not None:
        pipe = redis.pipeline(transaction=True)
        for event in events:
            pipe.xadd(key, {"data": json.dumps(event, ensure_ascii=False)}, maxlen=_STREAM_MAXLEN)
        done = any(str(e.get("type")) in ("RUN_FINISHED", "RUN_ERROR") for e in events)
        if done:
            pipe.xadd(key, {"data": "__END__"}, maxlen=_STREAM_MAXLEN)
        pipe.expire(key, _TTL_S)
        await pipe.execute()
        return len(events)
    run = _memory_run(run_id)
    run.thread = str(thread_id)  # type: ignore[attr-defined]
    for event in events:
        run.events.append((f"{time.time_ns()}", event))
    if any(str(e.get("type")) in ("RUN_FINISHED", "RUN_ERROR") for e in events):
        run.events.append(("end", {}))
        run.done = True
    return len(events)


async def iter_stream(
    thread_id: uuid.UUID | str,
    run_id: str,
    last_id: str = "0",
) -> AsyncIterator[dict[str, Any] | None]:
    """Yield stored AG-UI events, then follow until the end marker.

    Yields ``None`` as a heartbeat tick when nothing arrives within one
    poll, and a final ``RUN_ERROR`` event if the watchdog deadline passes
    without an end marker. Closes after ``__END__``.
    """
    deadline = time.monotonic() + _MAX_TOTAL_S
    idle_deadline = time.monotonic() + _MAX_IDLE_S
    redis = await get_redis()
    key = _stream_key(thread_id, run_id)
    if redis is not None:
        # Dedicated connection: a cancelled blocking XREAD corrupts the
        # shared pool's connection (production incident 2026-09-14).
        client = await open_redis()
        if client is None:  # pragma: no cover — get_redis succeeded above
            return
        cursor = last_id
        import redis.exceptions  # noqa: PLC0415

        redis_errors = (
            redis.exceptions.TimeoutError,  # NOT a builtin TimeoutError subclass
            redis.exceptions.ConnectionError,  # NOT a builtin ConnectionError subclass
            TimeoutError,
            ConnectionError,
        )
        try:
            while time.monotonic() < deadline:
                try:
                    resp = await client.xread({key: cursor}, block=_XREAD_BLOCK_MS, count=200)
                except asyncio.CancelledError:
                    raise
                except redis_errors as exc:  # noqa: PERF203
                    logger.warning("agui stream xread failed for %s: %s", run_id, exc)
                    yield {"type": "RUN_ERROR", "message": "The agent event stream was interrupted."}
                    return
                if not resp:
                    if time.monotonic() > idle_deadline:
                        yield {"type": "RUN_ERROR", "message": "The agent run stopped responding before finishing."}
                        return
                    yield None
                    continue
                idle_deadline = time.monotonic() + _MAX_IDLE_S
                for _stream, entries in resp:
                    for entry_id, fields in entries:
                        cursor = entry_id.decode() if isinstance(entry_id, bytes) else str(entry_id)
                        raw = fields.get(b"data") or fields.get("data")
                        payload = raw.decode() if isinstance(raw, bytes) else str(raw or "")
                        if payload == "__END__":
                            return
                        try:
                            yield json.loads(payload)
                        except (ValueError, TypeError):
                            continue
            yield {"type": "RUN_ERROR", "message": "The agent run exceeded its total time budget."}
        finally:
            try:
                await client.aclose()
            except Exception:  # noqa: BLE001
                pass
        return
    run = _memory_run(run_id)
    index = 0
    idle_deadline = time.monotonic() + _MAX_IDLE_S
    while time.monotonic() < deadline:
        while index < len(run.events):
            marker_id, event = run.events[index]
            index += 1
            if marker_id == "end":
                return
            if last_id not in ("0", "$") and marker_id <= last_id:
                continue
            idle_deadline = time.monotonic() + _MAX_IDLE_S
            yield event
        if run.done:
            return
        if time.monotonic() > idle_deadline:
            yield {"type": "RUN_ERROR", "message": "The agent run stopped responding before finishing."}
            return
        await asyncio.sleep(0.3)
        yield None
    yield {"type": "RUN_ERROR", "message": "The agent run exceeded its total time budget."}
